### ISSUE TITLE
RStudio SVG disappeared

### ISSUE THREAD

**Issue by jayhesselberth** [tidyverse/tidyverse.org#368]
This link broke at some point: https://www.tidyverse.org/rstudio-logo.svg

pkgdown [expects it to work](https://pkgdown.r-lib.org/) (see broken img under "Developers" in the sidebar)

**Comment by batpigandme** [comment]
@apreshill are you wise to this one?

It's still under `/public` when I look locally, but that directory is in the `.gitignore`.

It _is_ there when I look at the dummied-up <https://tverse-migration.netlify.com/rstudio-logo.svg>, but not in <http://re-re-revise.netlify.com/>

**Comment by batpigandme** [comment]
OK, so we've figured out how to put it back there (it has to go under the static directory), but are now wondering if this is really the best place for it, given it's not used anywhere else in the Hugo site (it seems). @hadley, I assume there was a rationale behind it, but wanted to double check before moving on it

**Comment by batpigandme** [comment]
It also exists in the actual RStudio site: https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg

**Comment by apreshill** [comment]
as @batpigandme mentioned, this image file is never used in the site, so I removed it because I didn't realize there were external links to the image- there were a lot of files in the site's directories that were unused and made it difficult to maintain. To restore it, we could add it back into `static/` and this link would work:

https://www.tidyverse.org/rstudio-logo.svg

Ideally, it would be nice to add it to `static/images/` so the new link would be: https://www.tidyverse.org/images/rstudio-logo.svg

The footer in the current site is pulling this image:

https://github.com/tidyverse/tidyverse.org/blob/master/themes/hugo-tourmaline/static/css/images/logoRStudioWhite.svg

**Comment by jayhesselberth** [comment]
I think there are actually several sites that depend on this link (e.g. it's broken in the same way onhttps://dplyr.tidyverse.org/) so restoring it here would be the easiest fix.

**Comment by apreshill** [comment]
See also: https://github.com/tidyverse/tidyverse.org/pull/22

Since this happened before, it may be worth thinking about a dose of prevention- something as simple as a `README` in the `static/` folder that essentially says "Even though the file `rstudio-logo.svg` is used in none of this site's contents, please leave as X other things depend on this link to work."

**Comment by batpigandme** [comment]
Closed by #371
