### ISSUE TITLE
Problems Instalalling Tidyverse

### ISSUE THREAD

**Issue by miguelyogui** [tidyverse/tidyverse.org#629]
I'm having trouble running Tidyverse.

Thanks to anyone who helps..

I'm using R version 4.2.2 (2022-10-31 ucrt).

When calling the library, the following error appears:
> library("tidyverse")
Error: package or namespace load failed for 'tidyverse':
 .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: NULL
  error: package or namespace load failed for 'ggplot2' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'utf8'

I've uninstalled, reinstalled, installed the package manually, and nothing calls the library.
What can it be?

**Comment by batpigandme** [comment]
This repo is actually for the tidyverse.org website/blog as opposed to the package.

Before posting this in the tidyverse repo, though, you might try asking on [community](https://community.rstudio.com/). If it turns out to be a bug in the package itself, then you can always open an issue in the repo once you've tried suggestions folks offer there.

Thanks 🙂
